Changes to _rerender and _expire scripts to: Not run out of memory in render_expired Store all of stdout and stderr from render_expired to detect memory issues Comment tile expiry plans when high-zoom tiles are created.

diff --git a/openstreetmap-tiles-update-expire b/openstreetmap-tiles-update-expire
--- a/openstreetmap-tiles-update-expire
+++ b/openstreetmap-tiles-update-expire
@@ -40,13 +40,22 @@ RUNLOG=$LOG_DIR/run.log
 # "render_expired" can optionally delete (and/or dirty) tiles above a certail
 # threshold rather than rendering them.
 # Here we expire (but don't immediately rerender) tiles between zoom levels 
-# 13 and 18 and delete between 19 and 25,
-# and pretend that zooms 26 through 28 do not exist.
+# 13 and 18 and delete between 19 and 20, and pretend that zooms 21 through
+# 28 do not exist.
+#
+# The value of EXPIRY_MAXZOOM here is limited by the way that render_expired
+# uses memory - it tries to create an array of "all metatiles" and only
+# process each one once.  This makes sense at low(er) zooms, but fails at
+# higher ones.  If it fails render_expired will output
+# "not enough memory available." to stderr - the point at which it does that
+# will depend on the resources available on a particular system.
+# A separate mechanism (e.g. nightly deletion) must handle zoom levels between
+# EXPIRY_MAXZOOM below and the MAX_ZOOM set in render_config.h
 #------------------------------------------------------------------------------
 EXPIRY_MINZOOM=13
 EXPIRY_TOUCHFROM=13
 EXPIRY_DELETEFROM=19
-EXPIRY_MAXZOOM=25
+EXPIRY_MAXZOOM=20
 
 #*************************************************************************
 #*************************************************************************
@@ -165,19 +174,28 @@ fi
     m_ok "expiring tiles"
 #------------------------------------------------------------------------------
 # When expiring tiles we need to define the style sheet if it's not "default".
-# in this case it's "ajt".
+# In this case it's "ajt".
 # Previously all tiles on the "dirty" list between $EXPIRY_MINZOOM and 
 # $EXPIRY_MAXZOOM were dirtied.  We currently re-render 
 # tiles >= $EXPIRY_MINZOOM and < $EXPIRY_DELETEFROM, expiry from 14 and 
 # delete >= $EXPIRY_DELETEFROM and <= $EXPIRY_MAXZOOM.
-# The default path to renderd.sock is fixed.
+# The path to renderd.sock is passed as it is not the default.
+# All output from stdout and stderr is kept to enable us to spot memory issues.
 #------------------------------------------------------------------------------
-    if ! render_expired --map=ajt --min-zoom=$EXPIRY_MINZOOM --touch-from=$EXPIRY_TOUCHFROM --delete-from=$EXPIRY_DELETEFROM --max-zoom=$EXPIRY_MAXZOOM -s /var/run/renderd/renderd.sock < "$EXPIRY_FILE.$$" 2>&1 | tail -8 >> "$EXPIRYLOG"; then
+    date >> "$EXPIRYLOG"
+    date >> "$EXPIRYLOG.1"
+    if ! render_expired --map=ajt --min-zoom=$EXPIRY_MINZOOM --touch-from=$EXPIRY_TOUCHFROM --delete-from=$EXPIRY_DELETEFROM --max-zoom=$EXPIRY_MAXZOOM -s /var/run/renderd/renderd.sock < "$EXPIRY_FILE.$$" 2>> "$EXPIRYLOG.1" >> "$EXPIRYLOG"; then
         m_info "Expiry failed"
     fi
 
+    date >> "$EXPIRYLOG"
+    date >> "$EXPIRYLOG.1"
     rm "$EXPIRY_FILE.$$"
 
+#------------------------------------------------------------------------------
+# Only remove the lock file after expiry (if system is slow we want to delay
+# the next import, not have multiple render_expired processes running)    
+#------------------------------------------------------------------------------
     freelock "$LOCK_FILE"
    
     m_ok "Done with import"
